### REGISTER CUSTOMER
POST http://localhost:5000/customer
Content-Type: application/json

{
    "FirstName": "John",
    "LastName": "Doe",
    "Email": "john.doe@example.com",
    "Phone": "123456789",
    "Address": "123 Main Street",
    "Username":"johnDoe",
    "Password":"I@mrich254"
}

### LOGIN CUSTOMER
POST http://localhost:5000/customer/login
Content-Type: application/json

{
    "Email": "john.doe@example.com",
    "Password":"I@mrich254"
}

### GET ALL CUSTOMERS
GET http://localhost:5000/customer/all
Content-Type: application/json

### GET CUSTOMER BY ID
GET http://localhost:5000/customer/123456789
Content-Type: application/json

### UPDATE CUSTOMER
PUT http://localhost:5000/customer/update/123456789
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john.doe@example.com",
    "phone": "987654321",
    "address": "456 Oak Avenue"
}

### DELETE CUSTOMER
DELETE http://localhost:5000/customer/delete/123456789
Content-Type: application/json
